## Nornir Config File 
---
core:

  num_workers: 100

inventory:

  plugin: "nornir.plugins.inventory.simple.SimpleInventory"

  options: 

    host_file: "/tmp/nornir/inventory/hosts.yml"

    group_file: "/tmp/nornir/inventory/groups.yml"

    defaults_file: "/tmp/nornir/inventory/defaults.yml"
